### ISSUE TITLE
Inconsistent fetch status results

### ISSUE THREAD

**Issue by gertjandemulder** [SolidLabResearch/generic-data-viewer-react-admin#59]
The fetch status shows different results for the same query & authenticated user.

In the following example, the authenticated user, Texon, executes a query over its own data sources.
Hence, every data source's fetch status should be successful (as is the case in the correct example below).
However, the generic data viewer sometimes shows inconsistent results (cfr. incorrect example).

## Correct

![gdv-fetch-status-ok](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/assets/9964105/3d59371e-9a2d-4103-a073-a77751d0723c)

## Incorrect

![gdv-fetch-status-nok](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/assets/9964105/f005d87c-6cc8-446f-8dba-ddb23c5c0e06)

**Comment by mvanbrab** [comment]
The cause of this issue is Comunica's caching. I can solve this in two ways (in fact I tested both):

1. Allow fetch status to have 3 values: "Query was successful" / "Query failed" / "Query result reused from cache". This solution correctly represents the way Comunica is used in the code, but **might confuse the user**, because the resulting display depends on execution order of queries sharing some sources.
![afbeelding](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/assets/6448245/d6509247-c589-4ec0-bd21-00e9ec5fd49e)

2. Modify the code to disable Comunica caching (`myEngine.invalidateHttpCache(source)`). This straightforward solution includes some performance loss in the case of queries sharing some sources, but it **doesn't confuse the user**.

@gertjandemulder @bjdmeest Please help me choose.

**Comment by bjdmeest** [comment]
can't you just use the same status icon for 'query result reused from cache'? user doesn't care whether it's from cache or remote, no?

**Comment by gertjandemulder** [comment]
> can't you just use the same status icon for 'query result reused from cache'? user doesn't care whether it's from cache or remote, no?

+1

**Comment by mvanbrab** [comment]
Solved as proposed in feedback above.

**Comment by mvanbrab** [comment]
I have to reopen this issue for the following reason, not covered in above solution.
* In a query, where Comunica context property "lenient" is set true, the Fetch status is not shown as failed for resources where authentication failed.

This is a screenshot of such situation. In this case, the authenticated user (brand) does not have access to the first source.
![image](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/assets/6448245/0504adb8-a3ca-4801-8eea-c8132dd99fab)

Remark that in this screenshot the (currently experimental code behind the "Verified" column, when executed, tries to fetch the source again and sees the unavailability indeed.

**Comment by mvanbrab** [comment]
I think [this](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/blob/e14d249e94829f7f7a46d2ba4b372fec92b82afd/src/dataProvider/SparqlDataProvider.js#L241). What if the response code is not OK?
