### ISSUE TITLE
Behaviour on no access: long error message, eaternal page loading

### ISSUE THREAD

**Issue by mvanbrab** [SolidLabResearch/generic-data-viewer-react-admin#64]
When not logged in and executing a query accessing a protected source, a long technical error message appears but disaappears before you can read it and next the page loading continues eaternally.

Test:
- start server
- do NOT login
- execute query "A list of my favorite books"

**Comment by axellorreyne** [comment]
When a source for a query requires authentication and the user is not logged in or does not have access to one or more of the sources listed in the configuration, I attempt to catch the error thrown by the Comunica query engine and return an empty list as a result, emulating the behavior of a query that simply returns no quads/bindings such as [this](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/blob/8826361b903a7c5c34e1755c54f772354687b1cf/src/config.json#L82-L91) one. (The query that requires authentication that I used for debugging this issue was [this](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/blob/8826361b903a7c5c34e1755c54f772354687b1cf/src/config.json#L62-L71) one).

In [this](41c59d18c4418c7ec8619442e03b5641d11f3ee8) commit I attempted to fix this problem by making sure that no results returned by the dataprovider is correctly interpreted as an empty list and that the action bar is always shown in this case instead of a blank space where the result list component would be. To also catch the error thrown by the query that requires authentication, I simply [catch this error when the query is executed and I return an empty list](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/blob/8826361b903a7c5c34e1755c54f772354687b1cf/src/dataProvider/SparqlDataProvider.js#L182-L185), as if the query succeeded but returned no results. 


However, this did not fix the issue for the second query. The error message is no longer shown to the user but the eternal loading remains. 

After some debugging, I discovered that for both queries, the dataprovider will return an empty list upon calling the [getList](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/blob/8826361b903a7c5c34e1755c54f772354687b1cf/src/dataProvider/SparqlDataProvider.js#L25-L48) method, but the first query changes the state of [isLoading](https://github.com/SolidLabResearch/generic-data-viewer-react-admin/blob/8826361b903a7c5c34e1755c54f772354687b1cf/src/components/ListResultTable/ListResultTable.jsx#L24) to False upon completion of the query, while the second query never does and the state remains True, causing the eternal loading of the page, even though an empty list was still returned. 

After more extensive debugging of the dataprovider, I was unable to pinpoint the exact problem where the state hook for `isLoading` is never called to update its value to False. I expect it is some kind of problem with the asynchronous nature of the dataprovider and the react-admin library where some `Promise` is not correctly resolved somewhere, but after many attempts to fix this issue, I was unable to find the correct solution.

**Comment by mvanbrab** [comment]
May be fixed after a297298744a6ad0c6f097a9e1c7070ff02bfca6f. Waiting to close until more feedback.

**Comment by mvanbrab** [comment]
No negative feedback. Closing as solved.
